name: spdx_xml_to_markdown
version: 0.0.1

description: A package to convert a SPDX XML License source files into markdown.
homepage: https://ayan-b.github.io/spdx_xml_to_markdown/

environment:
  sdk: ">=2.4.0 <3.0.0"

dependencies:

dev_dependencies:
  test: ">=0.12.0 <2.0.0"
  pedantic: ^1.8.0
